# yaml
settings:
  input_dir: 'inputs'
  proton_data_dir: 'O:\poltar\HallB\RGC\data-p'
  deuteron_data_dir: 'O:\poltar\HallB\RGC\data-d'
  sample_data_dir: 'O:\poltar\HallB\RGC\sample_data'
  bcm_dir: 'O:\poltar\HallB\RGC\BCM\Mya'
  te_out_dir: '.\te'
  analysis:
    base_def: 0             # index of default baseline subtraction method
    sub_def: 0              # index of default fit subtraction method
    res_def: 0              # index of default results analysis method
    wings:                  # default bounds for fit wings, must be four numbers between 0 and 1
        - 0.01
        - 0.25
        - 0.75
        - 0.99
    sum_range:              # default bounds for range integration option
        - 0.35
        - 0.65
    d_fit_params:           # initial parameters for Dulya fits
        A : 0.03
        G : -0.00003
        r : 1.2
        wQ : 0.027
        wL : 32.69
        eta : -0.02
        xi : -0.001
  offline:
    start_run: 17264
    stop_run: 17273
